--- 
- hosts: webserver 
  tasks: 
  - name: Check the HTTPd package is installed 
    yum: 
      name: httpd 
      state: present 
    become: True 
  - name: Check the HTTPd service is running 
    service: 
      name: httpd 
      state: started 
      enabled: True 
    become: True 
  - name: Check HTTP can pass the firewall 
    firewalld: 
      service: http 
      state: enabled 
      permanent: True 
      immediate: True 
    become: True 
  - name: Check HTTPS can pass the firewall 
    firewalld: 
      service: https 
      state: enabled 
      permanent: True 
      immediate: True 
    become: True   
