--- 
- hosts:  webserver
  tasks: 
  - name: create webpage
    template: 
      src: hellworld.html.v2
      dest: /var/www/html/index.html 
      owner: root 
      group: root 
      mode: 0644 
    become: True 
